name: auto_diary_ai
description: "AIで自動的に日記を生成するFlutterアプリ"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # --- Map ---
  flutter_map: ^8.2.1  # 地図本体
  latlong2: ^0.9.1     # 座標クラス
  geolocator: ^14.0.2  # GPS取得

  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

  # --- UI / Utility Libraries ---
  flutter_animate: ^4.5.2
  flex_color_scheme: ^8.3.1
  google_fonts: ^6.3.2
  go_router: ^16.3.0
  smooth_page_indicator: ^1.2.1
  awesome_dialog: ^3.3.0
  fluttertoast: ^9.0.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_settings_ui: ^3.0.1
  dio: ^5.9.0
  photo_manager: ^3.9.0
  receive_sharing_intent: 1.8.0
  http: ^1.2.2
  html: ^0.15.4

  # --- Animated List / Scroll Animation ---
  flutter_staggered_animations: ^1.1.1
  animated_list_plus: ^0.4.3

  # --- Grouped List ---
  grouped_list: ^5.1.2

  # --- Localization packages ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations
    untranslated-messages-file: lib/l10n/untranslated_messages.txt
